Repository UNLV-CS472-672/2024-S-GROUP6-RW, pull requests merged in 2024-03, with the labels that each got.

#52 Delete frontend/yarn.lock
  frontend/yarn.lock
Labels: enhancement

#55 Implemented handlers and created handlers stubs for currently specified data models stored in the database.
  backend/TripsList.js
  backend/handlers/activity.go
  backend/handlers/auth.go
  backend/handlers/expense.go
  backend/handlers/invoice.go
  backend/handlers/profile.go
  backend/handlers/trip.go
  backend/handlers/user.go
  backend/main.go
  backend/models/activity.go
  backend/models/expense.go
  backend/models/friendRequest.go
  backend/models/invoice.go
  backend/models/model.go
  backend/models/profile.go
  backend/models/trip.go
  backend/models/user.go
  backend/utility/compare.go
  backend/utility/search.go
Labels: documentation, enhancement

#83 Added the missing packages to the package.json file. EMERGENCY FIX
  frontend/package.json
Labels: bug
